passThroughZMin: 0.05
passThroughZMax: 3.0
voxelGridX: 0.04
voxelGridY: 0.04
voxelGridZ: 0.04
minRequiredPointsOnLine: 3
distanceToLineTresh: 0.2
refineSurfaceRequired: false
worldFrame: /map
clusterHeightTresh: 0.4
maxClusterXYDimension: 1.5
clusterTolerance: 0.1;
clusterMinSize: 50
clusterMaxSize: 300
setup: hector
maxDistBetweenStairsPoints: 3.0
minHightDistBetweenAllStairsPoints: 0.02
planeSegDistTresh: 0.05
planeSegAngleEps: 0.2
hesseTresh: 0.1
