passThroughZMin: -0.1
passThroughZMax: 2.5
voxelGridX: 0.04
voxelGridY: 0.04
voxelGridZ: 0.04
minRequiredPointsOnLine: 4
distanceToLineTresh: 0.1
refineSurfaceRequired: false
worldFrame: /map
clusterHeightTresh: 0.3
maxClusterXYDimension: 2
clusterTolerance: 0.075
clusterMinSize: 50
clusterMaxSize: 500
setup: hector
maxDistBetweenStairsPoints: 3
minHightDistBetweenAllStairsPoints: 0.05
planeSegDistTresh: 0.03
planeSegAngleEps: 0.1
hesseTresh: 0.1
maxStairsWidth: 1.5
