#passThroughZMin: 0.0
#passThroughZMax: 1.5
#voxelGridX: 0.04
#voxelGridY: 0.04
#voxelGridZ: 0.04
#minRequiredPointsOnLine: 4
#distanceToLineTresh: 0.1
#refineSurfaceRequired: true
#worldFrame: /map
#clusterHeightTresh: 0.1
#clusterTolerance: 0.075
#clusterMinSize: 50
#clusterMaxSize: 200
#angleDeviationToXYPlane: 0.3
#setup: hector
#distTrashSegmentation: 0.05
#maxDistBetweenStairsPoints: 3.0



passThroughZMin: -0.5
passThroughZMax: 2.5
voxelGridX: 0.04
voxelGridY: 0.04
voxelGridZ: 0.04
minRequiredPointsOnLine: 3
distanceToLineTresh: 0.2
refineSurfaceRequired: false
worldFrame: /map
clusterHeightTresh: 0.4
maxClusterXYDimension: 1.0
clusterTolerance: 0.1;
clusterMinSize: 50
clusterMaxSize: 500
angleDeviationToXYPlane: 0.3
setup: hector
distTrashSegmentation: 0.05
maxDistBetweenStairsPoints: 3.0
minHightDistBetweenAllStairsPoints: 0.1
maxPlaneDeviation: 0.5
