#!/usr/bin/env python

import sys

import roslib

pkg = 'hector_rqt_joint_control'
roslib.load_manifest(pkg)

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone=pkg))
